
-- MySQL Script generated by MySQL Workbench
-- Fri Jul 10 12:55:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema face
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema face
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `face` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `face` ;

-- -----------------------------------------------------
-- Table `face`.`ORGS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `face`.`ORGS` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '递增ID',
  `PARENT_ID` INT NOT NULL COMMENT '上级组织ID',
  `NAME` VARCHAR(40) CHARACTER SET 'utf8' NOT NULL COMMENT '名称',
  `TYPE` INT NOT NULL DEFAULT '0' COMMENT '1顶级组织  0非顶级组织',
  `BAK` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '备注',
  PRIMARY KEY USING BTREE (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COMMENT = '组织'
ROW_FORMAT = COMPACT;


-- -----------------------------------------------------
-- Table `face`.`DEVICE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `face`.`DEVICE` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '递增ID',
  `CODE` VARCHAR(40) CHARACTER SET 'utf8' NOT NULL COMMENT '国标编码或类似的唯一编码',
  `ADDRESS` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL COMMENT '描述摄像头的位置',
  `RTSP` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL COMMENT 'rtsp://xxx 开始的可访问rtsp地址',
  `LON` DECIMAL(10,6) NOT NULL COMMENT '经度',
  `LAT` DECIMAL(10,6) NOT NULL COMMENT '纬度',
  `ORG_ID` INT NOT NULL COMMENT '所属组织ID',
  `STATUS` INT NOT NULL COMMENT '1有效 0失效',
  `CTIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `BAK` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '备注',
  `FACE_STRUCT` CHAR(255) CHARACTER SET 'tis620' NOT NULL DEFAULT '1' COMMENT '1人脸0结构化',
  PRIMARY KEY USING BTREE (`ID`),
  UNIQUE INDEX `AK_Key_2` USING BTREE (`CODE`) VISIBLE,
  UNIQUE INDEX `AK_Key_3` USING BTREE (`ADDRESS`) VISIBLE,
  UNIQUE INDEX `AK_Key_4` USING BTREE (`RTSP`) VISIBLE,
  INDEX `FK_Reference_10` USING BTREE (`ORG_ID`) VISIBLE,
  CONSTRAINT `FK_Reference_10`
    FOREIGN KEY (`ORG_ID`)
    REFERENCES `face`.`ORGS` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8
COMMENT = '视频源（摄像头）'
ROW_FORMAT = COMPACT;


-- -----------------------------------------------------
-- Table `face`.`MAP_CONFIG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `face`.`MAP_CONFIG` (
  `CONF_KEY` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL COMMENT '字段名',
  `CONF_VAL` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL COMMENT '字段值',
  `TYPE` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL COMMENT 'int | string | double',
  `INFO` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '说明',
  PRIMARY KEY USING BTREE (`CONF_KEY`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '地图配置'
ROW_FORMAT = COMPACT;


-- -----------------------------------------------------
-- Table `face`.`MODEL_MENU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `face`.`MODEL_MENU` (
  `CODE` VARCHAR(6) CHARACTER SET 'utf8' NOT NULL COMMENT '前两位一级菜单，三四位二级菜单',
  `NAME` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL COMMENT '菜单名称',
  `PATH` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '菜单路径',
  `ICON` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '图标',
  PRIMARY KEY USING BTREE (`CODE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPACT;


-- -----------------------------------------------------
-- Table `face`.`ROLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `face`.`ROLES` (
  `ROL_ID` INT NOT NULL AUTO_INCREMENT COMMENT '角色ID',
  `NAME` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL COMMENT '角色名称',
  `CTIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY USING BTREE (`ROL_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8
COMMENT = '角色'
ROW_FORMAT = COMPACT;


-- -----------------------------------------------------
-- Table `face`.`ROLE_DEVICE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `face`.`ROLE_DEVICE` (
  `ROL_ID` INT NOT NULL COMMENT '角色ID',
  `ORG_ID` INT NOT NULL COMMENT '组织ID',
  PRIMARY KEY USING BTREE (`ROL_ID`, `ORG_ID`),
  INDEX `FK_Reference_4` USING BTREE (`ORG_ID`) VISIBLE,
  CONSTRAINT `FK_Reference_11`
    FOREIGN KEY (`ROL_ID`)
    REFERENCES `face`.`ROLES` (`ROL_ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_Reference_4`
    FOREIGN KEY (`ORG_ID`)
    REFERENCES `face`.`ORGS` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPACT;


-- -----------------------------------------------------
-- Table `face`.`ROLE_MODEL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `face`.`ROLE_MODEL` (
  `ROLE_ID` INT NOT NULL COMMENT '角色ID',
  `CODE` VARCHAR(6) CHARACTER SET 'utf8' NOT NULL COMMENT '功能编码',
  PRIMARY KEY USING BTREE (`ROLE_ID`, `CODE`),
  INDEX `FK_Reference_7` USING BTREE (`CODE`) VISIBLE,
  CONSTRAINT `FK_Reference_6`
    FOREIGN KEY (`ROLE_ID`)
    REFERENCES `face`.`ROLES` (`ROL_ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_Reference_7`
    FOREIGN KEY (`CODE`)
    REFERENCES `face`.`MODEL_MENU` (`CODE`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPACT;


-- -----------------------------------------------------
-- Table `face`.`WARN_LIB_CODE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `face`.`WARN_LIB_CODE` (
  `LIB_CODE` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL DEFAULT '' COMMENT '底库编码',
  `LIB_NAME` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL COMMENT '底库名称',
  `IS_WARN` INT NOT NULL COMMENT '是否布控库  1是  0否',
  `CTIME` DATETIME NOT NULL COMMENT '创建时间',
  `WARN_TIME` DATETIME NOT NULL COMMENT '布控时间',
  `BAK` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '备注',
  `store` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL DEFAULT 'local' COMMENT '存储类型  local  remote',
  PRIMARY KEY USING BTREE (`LIB_CODE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '底库'
ROW_FORMAT = COMPACT;


-- -----------------------------------------------------
-- Table `face`.`ROLE_WARN_LIB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `face`.`ROLE_WARN_LIB` (
  `LIB_CODE` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL COMMENT '底库编码',
  `ROL_ID` INT NOT NULL COMMENT '角色ID',
  PRIMARY KEY USING BTREE (`LIB_CODE`, `ROL_ID`),
  INDEX `FK_Reference_12` USING BTREE (`ROL_ID`) VISIBLE,
  CONSTRAINT `FK_Reference_12`
    FOREIGN KEY (`ROL_ID`)
    REFERENCES `face`.`ROLES` (`ROL_ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_Reference_8`
    FOREIGN KEY (`LIB_CODE`)
    REFERENCES `face`.`WARN_LIB_CODE` (`LIB_CODE`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPACT;


-- -----------------------------------------------------
-- Table `face`.`SYS_CONFIG`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `face`.`SYS_CONFIG` (
  `CONF_KEY` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `CONF_VALUE` VARCHAR(1024) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `INFO` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
ROW_FORMAT = COMPACT;


-- -----------------------------------------------------
-- Table `face`.`SYS_LOGS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `face`.`SYS_LOGS` (
  `LOG_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '日志时间',
  `LOG_LVL` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL COMMENT '日志级别 INFO | WARN | ERROR',
  `LOG_MODEL` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL COMMENT '认证 | 预警 | 路人 | 轨迹搜索 ....',
  `LOG_MSG` TEXT CHARACTER SET 'utf8' NOT NULL COMMENT '日志内容',
  `USER_ID` INT NULL DEFAULT NULL,
  INDEX `Index_1` USING BTREE (`LOG_TIME`) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '系统日志'
ROW_FORMAT = COMPACT;


-- -----------------------------------------------------
-- Table `face`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `face`.`USERS` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '递增ID',
  `LOGIN` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL COMMENT '登录名',
  `PASSWD` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL COMMENT '密码的BASE64编码',
  `NAME` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL COMMENT '姓名',
  `STATUS` INT NOT NULL DEFAULT '1' COMMENT '1有效 0失效',
  `TYPE` INT NULL DEFAULT '0' COMMENT '1超级用户  0普通用户',
  `CTIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `BAK` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '备注',
  PRIMARY KEY USING BTREE (`ID`),
  UNIQUE INDEX `AK_Key_2` USING BTREE (`LOGIN`) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COMMENT = '用户'
ROW_FORMAT = COMPACT;


-- -----------------------------------------------------
-- Table `face`.`USER_ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `face`.`USER_ROLE` (
  `ROLE_ID` INT NOT NULL COMMENT '角色ID',
  `USER_ID` INT NOT NULL COMMENT '用户ID',
  PRIMARY KEY USING BTREE (`ROLE_ID`, `USER_ID`),
  INDEX `FK_Reference_2` USING BTREE (`USER_ID`) VISIBLE,
  CONSTRAINT `FK_Reference_2`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `face`.`USERS` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `FK_Reference_9`
    FOREIGN KEY (`ROLE_ID`)
    REFERENCES `face`.`ROLES` (`ROL_ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPACT;


-- -----------------------------------------------------
-- Table `face`.`librarycollision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `face`.`librarycollision` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `taskid` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '任务id',
  `status` VARCHAR(2) CHARACTER SET 'utf8' NULL DEFAULT '0' COMMENT '任务状态 0-开始，2结束',
  `starttime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '任务开始时间',
  `endtime` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '任务结束时间',
  `source_library` VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '源库名称',
  `dest_library` VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '目标库名称',
  `flag` VARCHAR(2) CHARACTER SET 'utf8' NULL DEFAULT '0' COMMENT '是否取消 0-否，1-是',
  `userid` VARCHAR(11) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '用户id标记',
  PRIMARY KEY USING BTREE (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPACT;


-- -----------------------------------------------------
-- Table `face`.`librarycollision_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `face`.`librarycollision_detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tid` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT 'librarycollision库里的taskid',
  `similarly` VARCHAR(10) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '相似度',
  `name` VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '名字',
  `nation` VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '民族',
  `sex` VARCHAR(5) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '性别',
  `identitycard` VARCHAR(30) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '身份证号码',
  `pic_url` VARCHAR(300) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '图片地址',
  `address` VARCHAR(500) CHARACTER SET 'utf8' NULL DEFAULT NULL COMMENT '地址',
  `createtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY USING BTREE (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPACT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
